import { NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';
import path from 'path';

export async function GET() {
  try {
    const { data: videos, error } = await supabase
      .from('videos')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) {
      throw error;
    }

    return NextResponse.json(videos || []);
  } catch (error) {
    console.error('Failed to read videos data', error);
    return NextResponse.json({ error: 'Failed to read videos data' }, { status: 500 });
  }
}

export async function POST(request: Request) {
  try {
    const formData = await request.formData();
    const file = formData.get('file') as File | null;
    const title = formData.get('title') as string;
    const description = formData.get('description') as string;
    const category = formData.get('category') as string;

    if (!file || !title || !category) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    // 1. Upload to Supabase Storage
    const ext = path.extname(file.name) || '.mp4';
    const fileName = `${Date.now()}-${Math.round(Math.random() * 1e9)}${ext}`;
    
    // We must pass the raw file buffer to Supabase Storage
    const { data: storageData, error: storageError } = await supabase.storage
      .from('videos')
      .upload(fileName, file, {
        cacheControl: '3600',
        upsert: false
      });

    if (storageError) {
      console.error('Storage error:', storageError);
      return NextResponse.json({ error: 'Failed to upload video to storage' }, { status: 500 });
    }

    // Get the public URL for the uploaded video
    const { data: publicUrlData } = supabase.storage
      .from('videos')
      .getPublicUrl(fileName);

    const videoUrl = publicUrlData.publicUrl;

    // 2. Insert metadata into Supabase Database
    const { data: dbData, error: dbError } = await supabase
      .from('videos')
      .insert([
        {
          title,
          description: description || '',
          category,
          video_url: videoUrl
          // id and created_at are auto-generated by Supabase
        }
      ])
      .select()
      .single();

    if (dbError) {
      console.error('Database error:', dbError);
      // Attempt to clean up storage if DB insert fails
      await supabase.storage.from('videos').remove([fileName]);
      return NextResponse.json({ error: 'Failed to save video metadata' }, { status: 500 });
    }

    return NextResponse.json({ message: 'Video uploaded successfully', video: dbData }, { status: 201 });
  } catch (error) {
    console.error('Upload error:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
