import { NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';
import path from 'path';
import fs from 'fs';
import fsPromises from 'fs/promises';

export async function GET() {
  try {
    const { data: videos, error } = await supabase
      .from('videos')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) {
      throw error;
    }

    return NextResponse.json(videos || []);
  } catch (error) {
    console.error('Failed to read videos data', error);
    return NextResponse.json({ error: 'Failed to read videos data' }, { status: 500 });
  }
}

export async function POST(request: Request) {
  try {
    const formData = await request.formData();
    const file = formData.get('file') as File | null;
    const title = formData.get('title') as string;
    const description = formData.get('description') as string;
    const category = formData.get('category') as string;

    if (!file || !title || !category) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    // 1. Upload to local file system (Hostinger)
    const ext = path.extname(file.name) || '.mp4';
    const fileName = `${Date.now()}-${Math.round(Math.random() * 1e9)}${ext}`;
    
    // Ensure directory exists
    const uploadDir = path.join(process.cwd(), 'public', 'uploads', 'videos');
    await fsPromises.mkdir(uploadDir, { recursive: true });
    
    // Save file
    const filePath = path.join(uploadDir, fileName);
    
    // Stream file to disk to avoid out-of-memory errors for large files
    const writeStream = fs.createWriteStream(filePath);
    const fileStream = file.stream();
    const reader = fileStream.getReader();

    try {
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        writeStream.write(Buffer.from(value));
      }
      writeStream.end();
    } catch (err) {
      writeStream.end();
      throw err;
    }

    const videoUrl = `/uploads/videos/${fileName}`;

    // 2. Insert metadata into Supabase Database
    const { data: dbData, error: dbError } = await supabase
      .from('videos')
      .insert([
        {
          title,
          description: description || '',
          category,
          video_url: videoUrl
          // id and created_at are auto-generated by Supabase
        }
      ])
      .select()
      .single();

    if (dbError) {
      console.error('Database error:', dbError);
      // Attempt to clean up local file if DB insert fails
      await fs.unlink(filePath).catch(() => {});
      return NextResponse.json({ error: `Database error: ${dbError.message || dbError.details || 'Failed to save metadata'}` }, { status: 500 });
    }

    return NextResponse.json({ message: 'Video uploaded successfully', video: dbData }, { status: 201 });
  } catch (error: any) {
    console.error('Upload error:', error);
    return NextResponse.json({ error: error.message || 'Internal Server Error', stack: error.stack }, { status: 500 });
  }
}
